name: "Pull reReviewsviews reminder action"
description: "Automatically send notification"
branding:
  icon: "bell"
  color: "red"
inputs:
  slack-webhook:
    description: "Webhook URL"
    required: true
  channel:
    description: "channel Name"
    required: true
  repo:
    description: "repo Name"
    required: true
  organization:
    description: "organization name"
    required: false
  slack-lookups:
    description: "Map GitHub username to Slack user IDs"
    required: false
    default: false
runs:
  using: "node12"
  main: "dist/index.js"
